# Generated by Django 4.0.10 on 2024-08-15 09:56

import apartment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(default=10.0)),
                ('price_per_m', models.FloatField(default=1.0)),
                ('apartment_sold', models.IntegerField(default=0)),
                ('total_area', models.FloatField(default=0)),
                ('residential_area', models.FloatField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('year_of_delivery', models.IntegerField(default=0)),
                ('house', models.CharField(max_length=100, null=True)),
                ('house_uz', models.CharField(max_length=100, null=True)),
                ('house_ru', models.CharField(max_length=100, null=True)),
                ('house_en', models.CharField(max_length=100, null=True)),
                ('finishing', models.CharField(max_length=100, null=True)),
                ('finishing_uz', models.CharField(max_length=100, null=True)),
                ('finishing_ru', models.CharField(max_length=100, null=True)),
                ('finishing_en', models.CharField(max_length=100, null=True)),
                ('view_from_window', models.CharField(max_length=100, null=True)),
                ('view_from_window_uz', models.CharField(max_length=100, null=True)),
                ('view_from_window_ru', models.CharField(max_length=100, null=True)),
                ('view_from_window_en', models.CharField(max_length=100, null=True)),
                ('bathroom', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100, null=True)),
                ('type_uz', models.CharField(max_length=100, null=True)),
                ('type_ru', models.CharField(max_length=100, null=True)),
                ('type_en', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('mortgage_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('brand_image', models.ImageField(blank=True, upload_to='brand-images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apartment.order')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.location')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apartment.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_shots', to='apartment.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.category'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.district'),
        ),
    ]
