# Generated by Django 4.0.10 on 2024-08-24 03:13

import apartment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=10.0, null=True, verbose_name='Narx')),
                ('price_per_m', models.FloatField(blank=True, default=1.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('mortgage_available', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Turar joy',
                'verbose_name_plural': 'Turar joylar',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brend')),
                ('apartment_sold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan Uylar')),
                ('year_join', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yil')),
                ('brand_image', models.ImageField(blank=True, upload_to='brand-images', verbose_name='Brend Logosi')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(blank=True, default=0, null=True, verbose_name='Umumiy maydon')),
                ('residential_area', models.FloatField(blank=True, default=0, null=True, verbose_name='Aholi yashash maydoni')),
                ('floor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qavat')),
                ('year_of_delivery', models.IntegerField(blank=True, default=0, null=True, verbose_name="Tayyor bo'lish sanasi")),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati')),
                ('house_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati')),
                ('house_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati')),
                ('house_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati')),
                ('finishing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon')),
                ('finishing_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon')),
                ('finishing_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon')),
                ('finishing_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon')),
                ('view_from_window', models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi")),
                ('view_from_window_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi")),
                ('view_from_window_en', models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi")),
                ('view_from_window_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi")),
                ('bathroom', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yuvinish honasi')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi')),
                ('type_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi')),
                ('type_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Xarakteristika',
                'verbose_name_plural': 'Xarakteristikalar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Features', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Xususiyat',
                'verbose_name_plural': 'Xususiyatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand')),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apartment.order')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='ApartmentShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apartment.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_shots', to='apartment.apartment')),
            ],
            options={
                'verbose_name': 'Turar joy rasmi',
                'verbose_name_plural': 'Turar joy rasmlari',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.category'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.characteristic'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.district'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='feature',
            field=models.ManyToManyField(blank=True, to='apartment.features'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.project'),
        ),
    ]
