# Generated by Django 4.0.10 on 2024-09-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentCharacteristic',
        ),
    ]
