# Generated by Django 4.0.10 on 2024-07-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentshots',
            options={},
        ),
    ]
