# Generated by Django 4.0.10 on 2024-08-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='location',
        ),
    ]
