<<<<<<< HEAD
# Generated by Django 4.0.10 on 2024-09-03 07:17
=======
# Generated by Django 4.0.10 on 2024-09-02 18:10
>>>>>>> e379f37d75ac012dc76b8651516c911ef0f40a00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentCharacteristic',
        ),
    ]
