# Generated by Django 4.0.10 on 2024-09-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartmentcharacteristic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentCharacteristic',
        ),
    ]
