# Generated by Django 4.0.10 on 2024-09-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_delete_apartmentcharacteristic'),
        ('rent_apartment', '0002_characteristic_remove_rentapartment_characteristic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
