# Generated by Django 4.0.10 on 2024-08-15 14:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_remove_district_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='apartment.apartment'),
        ),
    ]
