# Generated by Django 4.0.10 on 2024-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_apartmentshots_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
