# Generated by Django 4.0.10 on 2024-09-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_delete_apartmentcharacteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='features', to='apartment.features'),
        ),
    ]
