# Generated by Django 4.0.10 on 2024-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_location_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='apartment',
        ),
    ]
