# Generated by Django 4.0.10 on 2024-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
