# Generated by Django 4.0.10 on 2024-09-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='feature',
            new_name='features',
        ),
    ]
