# Generated by Django 4.0.10 on 2024-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_location_apartment'),
        ('rent_apartment', '0002_remove_rentapartment_location_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
