# Generated by Django 4.0.10 on 2024-07-31 06:47

import apartment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=apartment.models.upload_to),
        ),
        migrations.AlterField(
            model_name='apartmentshots',
            name='image',
            field=models.ImageField(null=True, upload_to=apartment.models.upload_to),
        ),
    ]
