# Generated by Django 4.0.10 on 2024-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characterisitc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(default=0)),
                ('residential_area', models.FloatField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('year_of_delivery', models.IntegerField(default=0)),
                ('house', models.CharField(max_length=100, null=True)),
                ('house_uz', models.CharField(max_length=100, null=True)),
                ('house_ru', models.CharField(max_length=100, null=True)),
                ('house_en', models.CharField(max_length=100, null=True)),
                ('finishing', models.CharField(max_length=100, null=True)),
                ('finishing_uz', models.CharField(max_length=100, null=True)),
                ('finishing_ru', models.CharField(max_length=100, null=True)),
                ('finishing_en', models.CharField(max_length=100, null=True)),
                ('view_from_window', models.CharField(max_length=100, null=True)),
                ('view_from_window_uz', models.CharField(max_length=100, null=True)),
                ('view_from_window_ru', models.CharField(max_length=100, null=True)),
                ('view_from_window_en', models.CharField(max_length=100, null=True)),
                ('bathroom', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100, null=True)),
                ('type_uz', models.CharField(max_length=100, null=True)),
                ('type_ru', models.CharField(max_length=100, null=True)),
                ('type_en', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='finishing_en',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='finishing_ru',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='finishing_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='house_en',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='house_ru',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='house_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='residential_area',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='type_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='view_from_window',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='view_from_window_en',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='view_from_window_ru',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='view_from_window_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='year_of_delivery',
        ),
        migrations.AddField(
            model_name='apartment',
            name='characteristic',
            field=models.ManyToManyField(to='apartment.characterisitc'),
        ),
    ]
