# Generated by Django 4.0.10 on 2024-09-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_rename_feature_apartment_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'ng'iroq uchun"),
        ),
    ]
