# Generated by Django 4.0.10 on 2024-08-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_characterisitc_remove_apartment_bathroom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characterisitc',
            new_name='Characterisitic',
        ),
    ]
