# Generated by Django 4.0.10 on 2024-08-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_rename_characterisitc_characterisitic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characterisitic',
            new_name='Characteristic',
        ),
    ]
