# Generated by Django 4.0.10 on 2024-08-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_rename_characterisitic_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvAndCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenience', models.BooleanField(blank=True, default=False, null=True)),
                ('condition', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='apartment',
            name='characteristics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.characteristic'),
        ),
    ]
