# Generated by Django 4.0.10 on 2024-08-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_apartment_brand_apartment_ctiy_apartment_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='company_logo',
        ),
    ]
