# Generated by Django 4.0.10 on 2024-08-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_convandcon_remove_apartment_characteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='convandcon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.convandcon'),
        ),
        migrations.AlterField(
            model_name='convandcon',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='convandcon',
            name='convenience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
