# Generated by Django 4.0.10 on 2024-08-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_apartment_convandcon_alter_convandcon_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='convandcon',
        ),
        migrations.AddField(
            model_name='apartment',
            name='convandcon',
            field=models.ManyToManyField(blank=True, to='apartment.convandcon'),
        ),
    ]
