# Generated by Django 4.0.10 on 2024-08-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_rename_ctiy_apartment_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='is_mortgage',
            new_name='mortgage_available',
        ),
    ]
