# Generated by Django 4.0.10 on 2024-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_remove_apartment_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='apartment.characteristic'),
        ),
    ]
