# Generated by Django 4.0.10 on 2024-08-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_category_apartment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='residential_are',
            new_name='residential_area',
        ),
    ]
