# Generated by Django 4.0.10 on 2024-08-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_rename_residential_are_apartment_residential_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='viev_from_window',
            new_name='view_from_window',
        ),
    ]
