# Generated by Django 4.0.10 on 2024-08-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_project_remove_apartment_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand'),
        ),
    ]
