# Generated by Django 4.0.10 on 2024-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_rename_viev_from_window_apartment_view_from_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='finishing_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='finishing_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='finishing_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='house_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='house_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='house_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='view_from_window_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='view_from_window_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='view_from_window_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
