# Generated by Django 4.0.10 on 2024-08-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_project_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='convandcon',
        ),
        migrations.DeleteModel(
            name='ConvAndCon',
        ),
    ]
