# Generated by Django 4.0.10 on 2024-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_banner_apartment_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
