# Generated by Django 4.0.10 on 2024-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_alter_apartment_options_alter_apartmentshots_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_sold',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='company_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='apartment_sold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sotilgan Uylar'),
        ),
        migrations.AddField(
            model_name='brand',
            name='year_join',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(blank=True, default=10.0, null=True, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='brand-images', verbose_name='Brend Logosi'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='total_area',
            field=models.FloatField(default=0, verbose_name='Umumiy maydon'),
        ),
    ]
