# Generated by Django 4.0.10 on 2024-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0018_remove_apartment_apartment_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='bathroom',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yuvinish honasi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='residential_area',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='total_area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Umumiy maydon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='type_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ko'rinish"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ko'rinish"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ko'rinish"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ko'rinish"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='year_of_delivery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
