# Generated by Django 4.0.10 on 2024-08-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0018_banner_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='banner',
        ),
    ]
