# Generated by Django 4.0.10 on 2024-08-06 06:20

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0019_remove_apartment_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
