# Generated by Django 4.0.10 on 2024-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0019_alter_characteristic_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='finishing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='finishing_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jarayon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qavat'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='house_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy holati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='residential_area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Aholi yashash maydoni'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='view_from_window_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Derazadan ko'rinishi"),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='year_of_delivery',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Tayyor bo'lish sanasi"),
        ),
    ]
