# Generated by Django 4.0.10 on 2024-08-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0020_alter_characteristic_finishing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='characteristics',
            new_name='characteristic',
        ),
    ]
