# Generated by Django 4.0.10 on 2024-08-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_rename_characteristics_apartment_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.project'),
        ),
    ]
