# Generated by Django 4.0.10 on 2024-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_apartment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='news')),
                ('content', models.TextField()),
            ],
        ),
    ]
