# Generated by Django 4.0.10 on 2024-08-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0022_apartment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_finish',
        ),
    ]
