# Generated by Django 4.0.10 on 2024-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0023_remove_apartment_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
