# Generated by Django 4.0.10 on 2024-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0024_remove_news_image_news_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
