# Generated by Django 4.0.10 on 2024-08-22 10:59

import apartment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0025_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apartment.models.upload_to, verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Xususiyat',
                'verbose_name_plural': 'Xususiyatlar',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='feature',
            field=models.ManyToManyField(blank=True, to='apartment.features'),
        ),
    ]
