# Generated by Django 4.0.10 on 2024-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0026_features_apartment_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Features', verbose_name='Rasm'),
        ),
    ]
