# Generated by Django 4.0.10 on 2024-08-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0026_remove_apartment_location_location_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentshots',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_shots', to='apartment.apartment'),
        ),
    ]
