# Generated by Django 4.0.10 on 2024-08-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0027_alter_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='mortgage_available',
            field=models.BooleanField(default=False, null=True, verbose_name='Ipoteka'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_per_m',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Narx kv metr'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room',
            field=models.IntegerField(blank=True, null=True, verbose_name='Xonalar soni'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoriya'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoriya'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoriya'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoriya'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proyekt'),
        ),
    ]
