# Generated by Django 4.0.10 on 2024-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0028_alter_apartment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
    ]
