# Generated by Django 4.0.10 on 2024-08-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0030_apartmentcharacteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='characteristic',
        ),
    ]
