# Generated by Django 4.0.10 on 2024-08-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0031_remove_apartment_characteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcharacteristic',
            options={'verbose_name': 'Xarakteristika', 'verbose_name_plural': 'Xarakteristikalar'},
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='value',
        ),
        migrations.AlterField(
            model_name='apartmentcharacteristic',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='qiymat'),
        ),
    ]
