# Generated by Django 4.0.10 on 2024-07-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price_per_m', models.FloatField(default=1.0)),
                ('apartment', models.IntegerField(default=2)),
                ('tenant_name', models.CharField(max_length=50, null=True)),
                ('tenant_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('company', models.CharField(max_length=50, null=True)),
                ('total_area', models.FloatField(default=0)),
                ('residential_are', models.FloatField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('year_of_delivery', models.IntegerField(default=0)),
                ('house', models.CharField(max_length=100, null=True)),
                ('finishing', models.CharField(max_length=100)),
                ('viev_from_window', models.CharField(max_length=100)),
                ('bathroom', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentApartmentShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent-apartments')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent_apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
            ],
            options={
                'verbose_name': 'Ijara turar joy rasmi',
                'verbose_name_plural': 'Ijara turar joy rasmlari',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rent_apartment.order')),
            ],
        ),
    ]
