# Generated by Django 4.0.10 on 2024-08-15 09:57

from django.db import migrations, models
import django.db.models.deletion
import rent_apartment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('price_per_m', models.FloatField(default=1.0)),
                ('apartment', models.IntegerField(default=2)),
                ('tenant_name', models.CharField(max_length=50, null=True)),
                ('tenant_image', models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to)),
                ('company', models.CharField(max_length=50, null=True)),
                ('total_area', models.FloatField(default=0)),
                ('residential_are', models.FloatField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('year_of_delivery', models.IntegerField(default=0)),
                ('house', models.CharField(max_length=100, null=True)),
                ('house_uz', models.CharField(max_length=100, null=True)),
                ('house_ru', models.CharField(max_length=100, null=True)),
                ('house_en', models.CharField(max_length=100, null=True)),
                ('finishing', models.CharField(max_length=100)),
                ('finishing_uz', models.CharField(max_length=100, null=True)),
                ('finishing_ru', models.CharField(max_length=100, null=True)),
                ('finishing_en', models.CharField(max_length=100, null=True)),
                ('view_from_window', models.CharField(max_length=100)),
                ('view_from_window_uz', models.CharField(max_length=100, null=True)),
                ('view_from_window_ru', models.CharField(max_length=100, null=True)),
                ('view_from_window_en', models.CharField(max_length=100, null=True)),
                ('bathroom', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('type_uz', models.CharField(max_length=100, null=True)),
                ('type_ru', models.CharField(max_length=100, null=True)),
                ('type_en', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.location')),
            ],
        ),
        migrations.CreateModel(
            name='RentApartmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentApartmentShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent_apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
            ],
        ),
        migrations.CreateModel(
            name='RentApartmentOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rent_apartment.rentapartmentorder')),
            ],
        ),
    ]
