# Generated by Django 4.0.10 on 2024-08-26 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import rent_apartment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharoit')),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharoit')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharoit')),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sharoit')),
            ],
            options={
                'verbose_name': 'Sharoit',
                'verbose_name_plural': 'Sharoitlar',
            },
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qulaylik')),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qulaylik')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qulaylik')),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qulaylik')),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
            },
        ),
        migrations.CreateModel(
            name='RentApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi')),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi')),
                ('price_per_m', models.FloatField(blank=True, default=1.0, null=True, verbose_name='Ijara narxi')),
                ('tenant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ismi')),
                ('tenant_image', models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to, verbose_name='Surati')),
                ('apartment_sold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Turar joy')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('description_en', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.category')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.characteristic')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.condition')),
                ('convenience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.convenience')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.district')),
            ],
            options={
                'verbose_name': 'Ijara turar joy',
                'verbose_name_plural': 'Ijara turar joylar',
            },
        ),
        migrations.CreateModel(
            name='RentApartmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Ijara turar joy zakaz',
                'verbose_name_plural': 'Ijara turar joy zakazlari',
            },
        ),
        migrations.CreateModel(
            name='RentApartmentShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_shots', to='rent_apartment.rentapartment')),
            ],
            options={
                'verbose_name': 'Ijara turar joy rasmi',
                'verbose_name_plural': 'Ijara turar joy rasmlari',
            },
        ),
        migrations.CreateModel(
            name='RentApartmentOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rent_apartment.rentapartmentorder')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzil nomi')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Manzil')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='apartment.apartment')),
                ('rent_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment')),
            ],
            options={
                'verbose_name': 'Manzillar',
            },
        ),
    ]
