# Generated by Django 4.0.10 on 2024-09-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_delete_apartmentcharacteristic'),
        ('rent_apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('label_uz', models.CharField(max_length=255, null=True)),
                ('label_en', models.CharField(max_length=255, null=True)),
                ('label_ru', models.CharField(max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='characteristics')),
            ],
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='condition',
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='condition',
            field=models.ManyToManyField(to='rent_apartment.condition'),
        ),
        migrations.CreateModel(
            name='ApartmentCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='qiymat')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='apartment.apartment')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rent_apartment.characteristic')),
                ('rent_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='rent_apartment.rentapartment')),
            ],
            options={
                'verbose_name': 'Xarakteristika',
                'verbose_name_plural': 'Xarakteristikalar',
            },
        ),
    ]
