# Generated by Django 4.0.10 on 2024-09-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Xarakteristika', 'verbose_name_plural': 'Xarakteristikalar'},
        ),
    ]
