# Generated by Django 4.0.10 on 2024-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='condition',
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='condition',
            field=models.ManyToManyField(blank=True, to='rent_apartment.condition'),
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='convenience',
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='convenience',
            field=models.ManyToManyField(blank=True, to='rent_apartment.convenience'),
        ),
    ]
