# Generated by Django 4.0.10 on 2024-07-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='RentApartmentOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='RentApartmentOrderItem',
        ),
        migrations.AlterModelOptions(
            name='rentapartmentshots',
            options={},
        ),
    ]
