# Generated by Django 4.0.10 on 2024-08-15 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_delete_location'),
        ('rent_apartment', '0002_remove_rentapartment_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='apartment.apartment'),
        ),
        migrations.AlterField(
            model_name='location',
            name='rent_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.rentapartment'),
        ),
    ]
