# Generated by Django 4.0.10 on 2024-07-31 07:09

from django.db import migrations, models
import rent_apartment.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0002_rename_order_rentapartmentorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='tenant_image',
            field=models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to),
        ),
        migrations.AlterField(
            model_name='rentapartmentshots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to),
        ),
    ]
