# Generated by Django 4.0.10 on 2024-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0002_characteristic_remove_rentapartment_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='characteristics'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
