# Generated by Django 4.0.10 on 2024-09-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0002_alter_characteristic_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentcharacteristic',
            name='apartment',
        ),
    ]
