# Generated by Django 4.0.10 on 2024-09-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_delete_apartmentcharacteristic'),
        ('rent_apartment', '0002_remove_rentapartment_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='qiymat')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='apartment.apartment')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apartment.characteristic')),
                ('rent_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='rent_apartment.rentapartment')),
            ],
            options={
                'verbose_name': 'Xarakteristika',
                'verbose_name_plural': 'Xarakteristikalar',
            },
        ),
    ]
