# Generated by Django 4.0.10 on 2024-09-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_delete_apartmentcharacteristic'),
        ('rent_apartment', '0003_remove_apartmentcharacteristic_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentcharacteristic',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='apartment.apartment'),
        ),
    ]
