# Generated by Django 4.0.10 on 2024-08-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_rename_ctiy_apartment_city'),
        ('rent_apartment', '0003_rentapartment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.brand'),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.city'),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.district'),
        ),
    ]
