# Generated by Django 4.0.10 on 2024-08-19 16:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0004_remove_location_lat_remove_location_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
