# Generated by Django 4.0.10 on 2024-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0004_apartmentcharacteristic_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='characteristics', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='label_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
    ]
