# Generated by Django 4.0.10 on 2024-08-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_rename_viev_from_window_apartment_view_from_window'),
        ('rent_apartment', '0004_rentapartment_brand_rentapartment_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.category'),
        ),
    ]
