# Generated by Django 4.0.10 on 2024-08-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0005_alter_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='finishing_en',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='finishing_ru',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='finishing_uz',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='house_en',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='house_ru',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='house_uz',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='residential_are',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='type_uz',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='view_from_window',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='view_from_window_en',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='view_from_window_ru',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='view_from_window_uz',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='year_of_delivery',
        ),
    ]
