# Generated by Django 4.0.10 on 2024-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0005_rentapartment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentapartment',
            old_name='viev_from_window',
            new_name='view_from_window',
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='finishing_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='finishing_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='finishing_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='house_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='house_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='house_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='type_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='view_from_window_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='view_from_window_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='view_from_window_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
