# Generated by Django 4.0.10 on 2024-08-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_banner_apartment_banner'),
        ('rent_apartment', '0006_rename_viev_from_window_rentapartment_view_from_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.banner'),
        ),
    ]
