# Generated by Django 4.0.10 on 2024-08-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0007_condition_convenience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Sharoit', 'verbose_name_plural': 'Sharoitlar'},
        ),
        migrations.AlterModelOptions(
            name='convenience',
            options={'verbose_name': 'Qulaylik', 'verbose_name_plural': 'Qulayliklar'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Manzillar'},
        ),
        migrations.AlterModelOptions(
            name='rentapartment',
            options={'verbose_name': 'Ijara turar joy', 'verbose_name_plural': 'Ijara turar joylar'},
        ),
        migrations.AlterModelOptions(
            name='rentapartmentorder',
            options={'verbose_name': 'Ijara turar joy zakaz', 'verbose_name_plural': 'Ijara turar joy zakazlari'},
        ),
        migrations.AlterModelOptions(
            name='rentapartmentshots',
            options={'verbose_name': 'Ijara turar joy rasmi', 'verbose_name_plural': 'Ijara turar joy rasmlari'},
        ),
    ]
