# Generated by Django 4.0.10 on 2024-08-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0007_rentapartment_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='banner',
        ),
    ]
