# Generated by Django 4.0.10 on 2024-08-21 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0008_alter_condition_options_alter_convenience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.condition'),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='convenience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_apartment.convenience'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi'),
        ),
    ]
