# Generated by Django 4.0.10 on 2024-09-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0008_rename_condition_rentapartment_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapartment',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='conditions', to='rent_apartment.condition'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='conveniences',
            field=models.ManyToManyField(blank=True, related_name='conveniences', to='rent_apartment.convenience'),
        ),
    ]
