# Generated by Django 4.0.10 on 2024-09-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0009_alter_rentapartment_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'ng'iroq uchun"),
        ),
    ]
