# Generated by Django 4.0.10 on 2024-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0010_alter_rentapartment_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapartment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='price_per_m',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Ijara narxi'),
        ),
    ]
