# Generated by Django 4.0.10 on 2024-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0011_alter_rentapartment_name_alter_rentapartment_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='company',
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='apartment_sold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Turar joy'),
        ),
        migrations.AddField(
            model_name='rentapartment',
            name='year_join',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yil'),
        ),
    ]
