# Generated by Django 4.0.10 on 2024-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0012_remove_rentapartment_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='apartment',
        ),
    ]
