# Generated by Django 4.0.10 on 2024-08-21 17:30

from django.db import migrations, models
import rent_apartment.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0013_remove_rentapartment_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapartment',
            name='tenant_image',
            field=models.ImageField(blank=True, null=True, upload_to=rent_apartment.models.upload_to, verbose_name='Surati'),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ismi'),
        ),
    ]
