# Generated by Django 4.0.10 on 2024-08-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0014_alter_rentapartment_tenant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='year_join',
        ),
    ]
