# Generated by Django 4.0.10 on 2024-08-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_rename_characteristics_apartment_characteristic'),
        ('rent_apartment', '0015_remove_rentapartment_year_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.characteristic'),
        ),
    ]
