# Generated by Django 4.0.10 on 2024-08-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_apartment', '0016_rentapartment_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapartmentshots',
            name='rent_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_shots', to='rent_apartment.rentapartment'),
        ),
    ]
