# Generated by Django 4.0.10 on 2024-08-26 05:25

import apartment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('text_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='Media', validators=[apartment.validators.validate_image_or_video])),
                ('content', models.TextField(blank=True, null=True, verbose_name='Kontent')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Kontent')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
