# Generated by Django 4.0.10 on 2024-08-09 09:42

import apartment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='news', validators=[apartment.validators.validate_image_or_video])),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
