# Generated by Django 4.0.10 on 2024-08-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
