# Generated by Django 4.0.10 on 2024-08-22 10:38

import apartment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0004_banner_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('text_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('text_en', models.CharField(blank=True, max_length=500, null=True)),
                ('text_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apartment.models.upload_to)),
            ],
        ),
    ]
