# Generated by Django 4.0.10 on 2024-08-22 10:48

import apartment.models
import apartment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0005_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Xususiyat', 'verbose_name_plural': 'Xususiyatlar'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apartment.models.upload_to, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='features',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='features',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='features',
            name='text_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='features',
            name='text_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=apartment.models.upload_to, validators=[apartment.validators.validate_image_or_video]),
        ),
    ]
