# Generated by Django 4.0.10 on 2024-08-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0006_alter_features_options_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
