# Generated by Django 4.0.10 on 2024-08-22 11:03

import apartment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0007_delete_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='Media', validators=[apartment.validators.validate_image_or_video]),
        ),
    ]
