# Generated by Django 4.0.10 on 2024-08-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_banners', '0008_alter_news_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Kontent'),
        ),
    ]
